Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(main.py:20913): Gdk-CRITICAL **: 14:07:16.883: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Demo mode False
It was a draw!
